//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataByShift
    {
        public int ID { get; set; }
        public Nullable<int> ShiftNumber { get; set; }
        public Nullable<int> ScalesNumberID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Productivity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual ScalesInformation ScalesInformation { get; set; }
    }
}
