//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scalesEntities2 : DbContext
    {
        public scalesEntities2()
            : base("name=scalesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataByDays> DataByDays { get; set; }
        public virtual DbSet<DataByHours> DataByHours { get; set; }
        public virtual DbSet<DataByMonth> DataByMonth { get; set; }
        public virtual DbSet<DataByShift> DataByShift { get; set; }
        public virtual DbSet<MeasurementData> MeasurementData { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<ScalesInformation> ScalesInformation { get; set; }
    }
}
